all: chat_server.c chat_client.c
	gcc -Wall -Wextra -Werror -pthread -o chat_server chat_server.c 
	gcc -Wall -Wextra -Werror -pthread -o chat_client chat_client.c
	gcc -Wall -Wextra -Werror -o chat_logger chat_logger.c

